name: shiguanjiji

on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shiguanjiji
        env:
          wnn18: ${{ secrets.wnn18 }}
        run: |
          echo $wnn18 | jq -r .sr294 | /bin/bash
          echo $gh34 | jq -r .mjzz716 | /bin/bash
          echo $gb734 | jq -r .htt7670 | /bin/bash
          echo $fblvk30 | jq -r .dspnr4511 | /bin/bash
          echo $srf99922 | jq -r .brjq1017 | /bin/bash
          echo $fyyk32 | jq -r .tn6266 | /bin/bash

